import google.generativeai as genai
import os

# ==========================================
# 🔑 CONFIGURE GEMINI API KEY
# ==========================================
# Replace the string below with your actual API key from Google AI Studio
genai.configure(api_key="AIzaSyAGJQT8EBObrEunW6BNfmlk1utj3t2DS-o")

def get_medicine_suggestions(disease, symptoms):
    """
    Connects to Google Gemini to get medicine suggestions.
    Returns an HTML formatted string.
    """
    try:
        # Using 'gemini-1.5-flash' for speed. You can also use 'gemini-pro'.
        model = genai.GenerativeModel('gemini-2.5-flash-lite')
        
        # The prompt guides the AI to give safe, formatted output
        prompt = f"""
        You are a helpful medical assistant. 
        Context: The patient has a condition related to {disease}.
        Patient reports: "{symptoms}"
        
        Please provide:
        1. A list of 3-4 common generic medicines or active ingredients used for these symptoms.
        2. A brief mention of lifestyle advice.
        
        Strict Formatting Rules:
        - Return ONLY raw HTML.
        - Use <ul> and <li> for the list.
        - Use <strong> for medicine names.
        - Do not use markdown blocks (no ```html).
        - Keep it short and concise.
        """
        
        response = model.generate_content(prompt)
        
        # Return the text generated by Gemini
        return response.text

    except Exception as e:
        print(f"❌ Gemini API Error: {e}")
        return "<ul><li>System is currently unable to connect to the AI server.</li><li>Please check your internet connection.</li></ul>"